### ISSUE TITLE
peoplebox und hyphenation

### ISSUE THREAD

**Issue by gdkrmr** [mamueller/Markus-LaTeX-poster-guide#3]
die Namen in `\peoplebox` tendieren dazu der automatischen Silbentrennung zum Opfer zu fallen, das sollte IMHO verhindert werden.
Kann man manuell machen mit `\hyphenation{FirstName}` `\hypenation{LastName}`, ist aber nicht besonderrs elegant.

**Comment by mamueller** [comment]
Ich finde es also gut wenn Du Verbesserungen einbaust.
Das gilt auch für kommende Vorschläge.(siehe unten)

konkret zur peoplebox
Meine peoplebox war ohnehin nur als Minimalvorschlag dedacht. (siehe meine
langen und breiten Bemerkungen zu meiner allgemeinen Strategie)
Ich würde daher vorschlagen den \hyphenation{FirstName} \hypenation{LastName}

Code in den  Beispielen einzubauen, aber nicht das Setzen der
Variablennamen Firstname und Lastname zu erzwingen.
(Fall jemand noch einen "Middlename" hat oder den zweiten Vornamen seiner
Großtante unbedingt einbauen will u.s.w
und vor allem damit man im Zweifelsfall als Anwender eben möglichst wenig
Vorgaben erfüllen muss.)
Wäre das in Deinem Sinne?

Eine andere wichtige Frage für mich ist  wie wir Deine Vorschläge den
potentiellen anderen Nutzern zugänglich machen.
Ich sehe die folgenden Möglichkeiten.

   1. Ich füge Dich einfach als Beitragenden für das Repository hinzu (Dazu
   brauchst Du einen github account)
   Solange wir uns über die Änderungen halbwegs einig sind -;), ist das die
   unkomplizierteste Art der Kollaboration.
   Du müsstest dann nicht fragen um offensichtliche Fehler zu beheben
   (Es gibt sicher noch einen Haufen Rechtschreibfehler die ich nicht
   gefunden habe)
   2. Du klonst, veränderst und schickst mir  einen Pullrequest. (Dann muss
   ich das ganze abnicken...seufz)
   3. Ich baue Deine gemailten Vorschläge eigenhändig ein... seufz

Grundlage für Variante eins und zwei wäre, dass Du alle Beispiele
durchlaufen lässt bevor Du engültig eincheckst,

so dass wir nicht versehentlich ein Template funktionsunfähig machen.


Was hältst Du davon?

Gruß

Markus




Am 21. Januar 2018 um 16:01 schrieb Guido Kraemer <notifications@github.com>
:

**Comment by gdkrmr** [comment]
du kannst mir gerne Schreibzugriff auf das Repository geben, ich werde versuchen nichts kaputt zu machen.
Ich habe für mich die Struktur ein bisschen verändert, das müsste ich erst rückgängig machen, bevor ich effektiv pushen/pull requests machen kann. Wo sollte ich am bessten mein eigene Poster reinstellen, so dass ich es bei mir lokal habe, aber nicht auf github? Unter ExamplePosters?

**Comment by mamueller** [comment]
Am 22. Januar 2018 um 20:57 schrieb Guido Kraemer <notifications@github.com>
:

> du kannst mir gerne Schreibzugriff auf das Repository geben, ich werde
> versuchen nichts kaputt zu machen.
> Ich habe für mich die Struktur ein bisschen verändert, das müsste ich erst
> rückgängig machen,
>
Vielleicht auch nicht, (ExamplePosters enthält ja unabhängige Ordner die
nur alle einen link auf die style files eine Etage darüber enthalten und
ein ein wenig structuriertes images Verzeichnis voraussetzen aber sonst
kannst Du ja machen was Du willst.

> bevor ich effektiv pushen/pull requests machen kann. Wo sollte ich am
> bessten mein eigene Poster reinstellen, so dass ich es bei mir lokal habe,
> aber nicht auf github? Unter ExamplePosters?
>
Genau.

Damit ich dir den Zugang freigeben kann, brauche ich den Github Usernamen.

Gruß
Markus

**Comment by gdkrmr** [comment]
hehe, ich dachte, den siehst du, wir sind ja auf github: gdkrmr

**Comment by mamueller** [comment]
;-)
Sorry, hatte ich gar nicht mitbekommen (habe einfach meine mail abgearbeitet)
Habe Dich aber schon vorgestern als contributor eingestellt. (Hoffentlich erfolgreich)
Es müsste also schon gehen.

Viele Grüße
Markus

**Comment by gdkrmr** [comment]
ja, ich bin inzwischen Contributor. Mein Poster ist fast fertig, soll dieses Template über das SAB Meeting hinaus verwendet werden?

**Comment by mamueller** [comment]
Ich weiß von nichts und frage mich ob ich fragen soll...

Warum erkläre ich Dir gerne mal bei einem Kaffee.
Wo sitzt Du denn?

Ich würde sagen, wir nutzen die Poster so wie es für uns Contributoren gut
ist.
(Wir müssen uns also nur untereinander und  nicht mit den Direktoren
einigen)

Ich bezweifle ehrlich gesagt, dass es tatsächlich ein *echtes* commitment
zu einem corporate desing seitens der Direktion gibt.
Die Templates wären ein guter Start, aber letzdendlich müsste man wirklich
mal Zeit investieren
um überhaupt erstmal die Schnittmenge zwischen dem mit den verschiedenen
Tools (inkscape ,Powerpoint , LaTeX ...)
Erreochbaren zu erkunden. (festgelegter Font, boxen?) um dann zu sehen was
man davon festklopfen will.
In der Vorbereitung des SAB war da vieles nicht zu Ende gedacht...

Ich fürchte, dass, wenn wir fragen, ob wir ein corporate design entwickeln
sollen,
das zwar viel zusätzliche Arbeit bedeutet, aber noch nicht mal klar ist ob
das überhaupt gewünscht ist.

Deshalb habe ich auch eher Beispiele gebaut als das Template optimiert...
Ich denke Du kannst Dir diese Freiheit auch nehmen.

Viele Grüße
Markus

2018-01-25 8:57 GMT+01:00 Guido Kraemer <notifications@github.com>:
